USE [master];
GO

ALTER DATABASE [BeamDWH] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE [BeamDWH];
GO


ALTER DATABASE [BeamConfig] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE [BeamConfig];
GO